name: install-cli-action smoke test
on:
  workflow_dispatch:
  push:

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
      - uses: YOUR_GITHUB_USERNAME/install-cli-action@jill/fix-vulnerabilities
      - run: op --version
