name: test-load-secrets-action

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_service_account:
    name: Service Account
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Load secret (service account)
        id: load_secrets
        uses: 1Password/load-secrets-action@v3.2.0
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: ${{ secrets.OP_SECRET_REF }}
          WEBSITE: op://Testing Vault/super-secret/url
          API_KEY: op://Testing Vault/super-secret-api-key/credential


      - name: Assert output present
        shell: bash
        run: |
          if [ -z "${{ steps.load_secrets.outputs.SECRET }}" ]; then
            echo "SECRET output is empty (service account)"
            exit 1
          fi
          echo "SECRET output is set (service account)"

  test_connect:
    name: Connect
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Launch Connect
        env:
          OP_CONNECT_CREDENTIALS: ${{ secrets.OP_CONNECT_CREDENTIALS }}
        run: |
          echo "$OP_CONNECT_CREDENTIALS" > 1password-credentials.json
          docker compose -f docker-compose.yml up -d

      - name: Load secret (connect)
        id: load_secrets
        uses: 1Password/load-secrets-action@v3.2.0
        env:
          OP_CONNECT_HOST: http://127.0.0.1:8080
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          SECRET: ${{ secrets.OP_SECRET_REF }}
          WEBSITE: op://Testing Vault/super-secret/url
          API_KEY: op://Testing Vault/super-secret-api-key/credential

      - name: Assert output present
        shell: bash
        run: |
          if [ -z "${{ steps.load_secrets.outputs.SECRET }}" ]; then
            echo "SECRET output is empty (connect)"
            exit 1
          fi
          echo "SECRET output is set (connect)"
